### ISSUE TITLE
上传文件报错，能帮忙看看么

### ISSUE THREAD

**Issue by lostmaniac** [XiaoMiku01/biliup-go#1]
anic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7d9756]

goroutine 43 [running]:
github.com/XiaoMiku01/biliup-go/upload.(*Up).upload.func2(0x0, 0x0?, 0xa00000?, 0xa00000?, {0xc000600000, 0xa00000, 0xa00000}, 0xc000128700?)
	/root/go/pkg/mod/github.com/!xiao!miku01/biliup-go@v0.1.3/upload/upload.go:265 +0xe96
created by github.com/XiaoMiku01/biliup-go/upload.(*Up).upload
	/root/go/pkg/mod/github.com/!xiao!miku01/biliup-go@v0.1.3/upload/upload.go:243 +0xd25

**Comment by XiaoMiku01** [comment]
上传的视频问题吗，换个视频也会吗

**Comment by lostmaniac** [comment]
是的，换个视频也会这样。

**Comment by lostmaniac** [comment]
应该是空指针没做异常处理

**Comment by XiaoMiku01** [comment]
多大的视频

**Comment by lostmaniac** [comment]
刚开始会大批量报分片重试
2022/11/18 11:48:36 重试发送分片 23
2022/11/18 11:48:36 重试发送分片 24
2022/11/18 11:48:36 重试发送分片 26
2022/11/18 11:48:36 重试发送分片 25
2022/11/18 11:48:36 重试发送分片 27
2022/11/18 11:48:36 重试发送分片 28
2022/11/18 11:48:36 重试发送分片 29
2022/11/18 11:48:36 重试发送分片 30
2022/11/18 11:48:36 重试发送分片 31
2022/11/18 11:48:36 重试发送分片 32
2022/11/18 11:48:36 重试发送分片 33
2022/11/18 11:48:36 重试发送分片 34
2022/11/18 11:48:36 重试发送分片 35
2022/11/18 11:48:36 重试发送分片 36
2022/11/18 11:48:36 重试发送分片 37
2022/11/18 11:48:36 重试发送分片 38
2022/11/18 11:48:36 重试发送分片 39
2022/11/18 11:48:36 重试发送分片 40
2022/11/18 11:48:36 重试发送分片 41
2022/11/18 11:48:36 重试发送分片 42
2022/11/18 11:50:36 重试发送分片 0
2022/11/18 11:50:36 重试发送分片 1
2022/11/18 11:50:36 重试发送分片 2
2022/11/18 11:50:36 重试发送分片 3
2022/11/18 11:50:36 重试发送分片 4
2022/11/18 11:50:36 重试发送分片 5
2022/11/18 11:50:36 重试发送分片 6
2022/11/18 11:50:36 重试发送分片 7
2022/11/18 11:50:36 重试发送分片 8
2022/11/18 11:50:36 重试发送分片 9
2022/11/18 11:50:36 重试发送分片 10

然后重试大概两三次并发，就报错了

文件大小420M，后面可能会上传10G左右的视频

**Comment by lostmaniac** [comment]
视频上传中...   0% |                                                                                                                                                                             | (0/424, 0 it/hr) [0s:0s]20
2022/11/18 11:44:35 重试发送分片 1
2022/11/18 11:44:35 重试发送分片 2
2022/11/18 11:44:35 重试发送分片 3
2022/11/18 11:44:35 重试发送分片 4
2022/11/18 11:44:35 重试发送分片 5
2022/11/18 11:44:35 重试发送分片 6
2022/11/18 11:44:35 重试发送分片 7
2022/11/18 11:44:35 重试发送分片 8
2022/11/18 11:44:35 重试发送分片 9
2022/11/18 11:44:35 重试发送分片 10
2022/11/18 11:44:35 重试发送分片 11
2022/11/18 11:44:35 重试发送分片 12
2022/11/18 11:44:35 重试发送分片 13
2022/11/18 11:44:35 重试发送分片 14
2022/11/18 11:44:35 重试发送分片 15
2022/11/18 11:44:35 重试发送分片 16
2022/11/18 11:44:35 重试发送分片 17
2022/11/18 11:44:35 重试发送分片 18
2022/11/18 11:44:35 重试发送分片 19
2022/11/18 11:44:35 重试发送分片 20
2022/11/18 11:44:35 重试发送分片 21
2022/11/18 11:44:35 重试发送分片 22
2022/11/18 11:44:35 重试发送分片 23
2022/11/18 11:44:35 重试发送分片 24
2022/11/18 11:44:35 重试发送分片 25
2022/11/18 11:44:35 重试发送分片 26
2022/11/18 11:44:35 重试发送分片 27
2022/11/18 11:44:35 重试发送分片 28
2022/11/18 11:44:35 重试发送分片 29
2022/11/18 11:44:35 重试发送分片 30
2022/11/18 11:44:35 重试发送分片 31
2022/11/18 11:44:35 重试发送分片 32
2022/11/18 11:44:35 重试发送分片 33
2022/11/18 11:44:35 重试发送分片 34
2022/11/18 11:44:35 重试发送分片 35
2022/11/18 11:44:35 重试发送分片 36
2022/11/18 11:44:35 重试发送分片 37
2022/11/18 11:44:35 重试发送分片 38
2022/11/18 11:44:35 重试发送分片 39
2022/11/18 11:44:35 重试发送分片 40
2022/11/18 11:44:35 重试发送分片 41
2022/11/18 11:44:35 重试发送分片 42
2022/11/18 11:46:35 重试发送分片 0
2022/11/18 11:46:35 重试发送分片 1
2022/11/18 11:46:35 重试发送分片 2
2022/11/18 11:46:35 重试发送分片 3
2022/11/18 11:46:35 重试发送分片 4
2022/11/18 11:46:35 重试发送分片 5
2022/11/18 11:46:36 重试发送分片 6
2022/11/18 11:46:36 重试发送分片 7
2022/11/18 11:46:36 重试发送分片 8
2022/11/18 11:46:36 重试发送分片 9
2022/11/18 11:46:36 重试发送分片 10
2022/11/18 11:46:36 重试发送分片 11
2022/11/18 11:46:36 重试发送分片 12
2022/11/18 11:46:36 重试发送分片 13
2022/11/18 11:46:36 重试发送分片 14
2022/11/18 11:46:36 重试发送分片 15
2022/11/18 11:46:36 重试发送分片 16
2022/11/18 11:46:36 重试发送分片 17
2022/11/18 11:46:36 重试发送分片 18
2022/11/18 11:46:36 重试发送分片 19
2022/11/18 11:46:36 重试发送分片 20
2022/11/18 11:46:36 重试发送分片 21
2022/11/18 11:46:36 重试发送分片 22
2022/11/18 11:46:36 重试发送分片 23
2022/11/18 11:46:36 重试发送分片 24
2022/11/18 11:46:36 重试发送分片 25
2022/11/18 11:46:36 重试发送分片 26
2022/11/18 11:46:36 重试发送分片 27
2022/11/18 11:46:36 重试发送分片 28
2022/11/18 11:46:36 重试发送分片 29
2022/11/18 11:46:36 重试发送分片 30
2022/11/18 11:46:36 重试发送分片 31
2022/11/18 11:46:36 重试发送分片 32
2022/11/18 11:46:36 重试发送分片 33
2022/11/18 11:46:36 重试发送分片 34
2022/11/18 11:46:36 重试发送分片 35
2022/11/18 11:46:36 重试发送分片 36
2022/11/18 11:46:36 重试发送分片 37
2022/11/18 11:46:36 重试发送分片 38
2022/11/18 11:46:36 重试发送分片 39
2022/11/18 11:46:36 重试发送分片 40
2022/11/18 11:46:36 重试发送分片 41
2022/11/18 11:46:36 重试发送分片 42
2022/11/18 11:48:36 重试发送分片 0
2022/11/18 11:48:36 重试发送分片 1
2022/11/18 11:48:36 重试发送分片 2
2022/11/18 11:48:36 重试发送分片 3
2022/11/18 11:48:36 重试发送分片 4
2022/11/18 11:48:36 重试发送分片 5
2022/11/18 11:48:36 重试发送分片 6
2022/11/18 11:48:36 重试发送分片 7
2022/11/18 11:48:36 重试发送分片 8
2022/11/18 11:48:36 重试发送分片 9
2022/11/18 11:48:36 重试发送分片 10
2022/11/18 11:48:36 重试发送分片 11
2022/11/18 11:48:36 重试发送分片 12
2022/11/18 11:48:36 重试发送分片 13
2022/11/18 11:48:36 重试发送分片 14
2022/11/18 11:48:36 重试发送分片 15
2022/11/18 11:48:36 重试发送分片 16
2022/11/18 11:48:36 重试发送分片 17
2022/11/18 11:48:36 重试发送分片 18
2022/11/18 11:48:36 重试发送分片 19
2022/11/18 11:48:36 重试发送分片 20
2022/11/18 11:48:36 重试发送分片 21
2022/11/18 11:48:36 重试发送分片 22
2022/11/18 11:48:36 重试发送分片 23
2022/11/18 11:48:36 重试发送分片 24
2022/11/18 11:48:36 重试发送分片 26
2022/11/18 11:48:36 重试发送分片 25
2022/11/18 11:48:36 重试发送分片 27
2022/11/18 11:48:36 重试发送分片 28
2022/11/18 11:48:36 重试发送分片 29
2022/11/18 11:48:36 重试发送分片 30
2022/11/18 11:48:36 重试发送分片 31
2022/11/18 11:48:36 重试发送分片 32
2022/11/18 11:48:36 重试发送分片 33
2022/11/18 11:48:36 重试发送分片 34
2022/11/18 11:48:36 重试发送分片 35
2022/11/18 11:48:36 重试发送分片 36
2022/11/18 11:48:36 重试发送分片 37
2022/11/18 11:48:36 重试发送分片 38
2022/11/18 11:48:36 重试发送分片 39
2022/11/18 11:48:36 重试发送分片 40
2022/11/18 11:48:36 重试发送分片 41
2022/11/18 11:48:36 重试发送分片 42
2022/11/18 11:50:36 重试发送分片 0
2022/11/18 11:50:36 重试发送分片 1
2022/11/18 11:50:36 重试发送分片 2
2022/11/18 11:50:36 重试发送分片 3
2022/11/18 11:50:36 重试发送分片 4
2022/11/18 11:50:36 重试发送分片 5
2022/11/18 11:50:36 重试发送分片 6
2022/11/18 11:50:36 重试发送分片 7
2022/11/18 11:50:36 重试发送分片 8
2022/11/18 11:50:36 重试发送分片 9
2022/11/18 11:50:36 重试发送分片 10
2022/11/18 11:50:36 重试发送分片 11
2022/11/18 11:50:36 重试发送分片 12
2022/11/18 11:50:36 重试发送分片 13
2022/11/18 11:50:36 重试发送分片 14
2022/11/18 11:50:36 重试发送分片 15
2022/11/18 11:50:36 重试发送分片 16
2022/11/18 11:50:36 重试发送分片 17
2022/11/18 11:50:36 重试发送分片 18
2022/11/18 11:50:36 重试发送分片 19
2022/11/18 11:50:36 重试发送分片 20
2022/11/18 11:50:36 重试发送分片 21
2022/11/18 11:50:36 重试发送分片 22
2022/11/18 11:50:36 重试发送分片 23
2022/11/18 11:50:36 重试发送分片 24
2022/11/18 11:50:36 重试发送分片 26
2022/11/18 11:50:36 重试发送分片 25
2022/11/18 11:50:36 重试发送分片 27
2022/11/18 11:50:36 重试发送分片 28
2022/11/18 11:50:36 重试发送分片 29
2022/11/18 11:50:36 重试发送分片 30
2022/11/18 11:50:36 重试发送分片 31
2022/11/18 11:50:36 重试发送分片 33
2022/11/18 11:50:36 重试发送分片 32
2022/11/18 11:50:36 重试发送分片 34
2022/11/18 11:50:36 重试发送分片 35
2022/11/18 11:50:36 重试发送分片 36
2022/11/18 11:50:36 重试发送分片 37
2022/11/18 11:50:36 重试发送分片 38
2022/11/18 11:50:36 重试发送分片 39
2022/11/18 11:50:36 重试发送分片 40
2022/11/18 11:50:36 重试发送分片 41
2022/11/18 11:50:36 重试发送分片 42
2022/11/18 11:52:36 重试发送分片 0
2022/11/18 11:52:36 重试发送分片 1
2022/11/18 11:52:36 重试发送分片 2
2022/11/18 11:52:36 重试发送分片 3
2022/11/18 11:52:36 重试发送分片 4
2022/11/18 11:52:36 重试发送分片 5
2022/11/18 11:52:36 重试发送分片 6
2022/11/18 11:52:36 重试发送分片 7
2022/11/18 11:52:36 重试发送分片 8
2022/11/18 11:52:36 重试发送分片 9
2022/11/18 11:52:36 重试发送分片 10
2022/11/18 11:52:36 重试发送分片 11
2022/11/18 11:52:36 重试发送分片 12
2022/11/18 11:52:36 重试发送分片 13
2022/11/18 11:52:36 重试发送分片 14
2022/11/18 11:52:36 重试发送分片 15
2022/11/18 11:52:36 重试发送分片 16
2022/11/18 11:52:36 重试发送分片 17
2022/11/18 11:52:36 重试发送分片 18
2022/11/18 11:52:36 重试发送分片 19
2022/11/18 11:52:36 重试发送分片 20
2022/11/18 11:52:36 重试发送分片 21
2022/11/18 11:52:36 重试发送分片 22
2022/11/18 11:52:36 重试发送分片 23
2022/11/18 11:52:36 重试发送分片 24
2022/11/18 11:52:36 重试发送分片 26
2022/11/18 11:52:36 重试发送分片 25
2022/11/18 11:52:36 重试发送分片 27
2022/11/18 11:52:36 重试发送分片 28
2022/11/18 11:52:36 重试发送分片 29
2022/11/18 11:52:36 重试发送分片 30
2022/11/18 11:52:36 重试发送分片 31
2022/11/18 11:52:36 重试发送分片 33
2022/11/18 11:52:36 重试发送分片 32
2022/11/18 11:52:36 重试发送分片 34
2022/11/18 11:52:36 重试发送分片 35
2022/11/18 11:52:36 重试发送分片 36
2022/11/18 11:52:36 重试发送分片 37
2022/11/18 11:52:36 重试发送分片 38
2022/11/18 11:52:36 重试发送分片 39
2022/11/18 11:52:36 重试发送分片 40
2022/11/18 11:52:36 重试发送分片 42
2022/11/18 11:52:36 重试发送分片 41
视频上传中...   2% |█████                                                                                                                                                                                                    anic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7d9756]

goroutine 43 [running]:
github.com/XiaoMiku01/biliup-go/upload.(*Up).upload.func2(0x0, 0x0?, 0xa00000?, 0xa00000?, {0xc000600000, 0xa00000, 0xa00000}, 0xc000128700?)
	/root/go/pkg/mod/github.com/!xiao!miku01/biliup-go@v0.1.3/upload/upload.go:265 +0xe96
created by github.com/XiaoMiku01/biliup-go/upload.(*Up).upload
	/root/go/pkg/mod/github.com/!xiao!miku01/biliup-go@v0.1.3/upload/upload.go:243 +0xd25

**Comment by XiaoMiku01** [comment]
当初写的时候没有测试很大的视频，不知道还有这个问题，我去测试一下看看吧

**Comment by lostmaniac** [comment]
哈哈哈，感谢。阿B最大的视频可以支持32GB的。

**Comment by XiaoMiku01** [comment]
https://github.com/XiaoMiku01/biliup-go/commit/64a41c81f2b8b2d0696e9e210e0e6407a7a1ae46 已修复
原因是读取视频时候没有限制 goroutine 的并发数量，导致内存爆炸了
我测试了一个 3G 的视频，现在应该没有问题了

**Comment by lostmaniac** [comment]
非常感谢，请问以后还有继续完善功能的计划吗？比如上传前先刷新cookie 有效期

**Comment by XiaoMiku01** [comment]
有空再说吧，之后可能会加，毕竟 cookie 相关不是这个项目的核心，而且现在并不知道频繁的刷新 cookie 账号会不会异常

**Comment by lostmaniac** [comment]
好的，我有时间也一起完善一下

**Comment by XiaoMiku01** [comment]
你如果感兴趣可以pr过来

**Comment by lostmaniac** [comment]
好的，感谢修复bug
